#' Prepare the observed SFS
#' @export
#' @import utils
#' @param observed This should be an observed multi-dimensional Site Frequency Spectrum as implemented in fastsimcoal2. Please ensure that you follow instructions from the package vignette concerning population naming and order.
#' @param FullPrior This should be the full prior as generated by the function \code{\link{makeprior}}.
#' @param ReducedPrior This should be the prior with invariant columns removed, as created by the function \code{\link{Prior_reduced}} \link{Prior_reduced}.
#' @param nclasses This is the number of classes that should be used to construct the binned mSFS, and should match that used for the Prior.
#' @param npops This should be equal to the number of potential species included in the analysis.
#' @param traitsfile This should be the name of the traits file for the observed data. Formatting follows the vignette.
#' @param threshold The percentage of individuals used to build the mSFS. This is relevant if you used a downsampling approach to build the mSFS from the observed data, but used the original number of individuals for generating models in delimitR.



prepobserved<- function(observed, FullPrior,ReducedPrior,nclasses,npops,traitsfile, threshold){
  system(paste("awk 'NR == 0 || NR % 3 == 0' ",observed,".obs > ",observed,"_processed.obs",sep=""))
  system(paste('python ',system.file(package="delimitR"), '/', 'SFS_CreateBinned_', npops, 'pops.py ',traitsfile,' ', observed, '_processed.obs ',threshold, " ", nclasses,' ',observed,'_binned.obs',sep=""))


  #Read in your observed data and remove columns that were removed from the prior due to a lack of variation.
  Observed <- utils::read.csv(paste(observed,'_binned.obs',sep=""), header = FALSE, sep = "\t")
  names(Observed) <- names(FullPrior)
  tokeep <- as.vector(names(ReducedPrior))
  Observed_Reduced <- subset(Observed, select = c(tokeep))
  names(Observed_Reduced)<-names(ReducedPrior)
  return(Observed_Reduced)
}

