#' Prepare the reduced SFS by removing bins of the SFS with no variance.s
#' @export
#'
#' @param FullPrior This should be the full prior as generated by the function \code{\link{makeprior}} \link{makeprior}.

Prior_reduced <- function(FullPrior){
  Models <- as.factor(FullPrior[,'Model'])
  summary(Models)
  FullPriorRed <- FullPrior
  FullPriorRed['Model'] <- NULL
  Prior_Reduced <- FullPriorRed[sapply(FullPriorRed, function(x) length(levels(factor(x)))>1)]
  Prior_Reduced <- as.data.frame(Prior_Reduced)

}


#' Build the RF classifier.
#' @export
#' @import abcrf
#' @param FullPrior This should be the full prior as generated by the function \code{\link{makeprior}} \link{makeprior}.
#' @param ReducedPrior This should be the prior with invariant columns removed, as created by the function \code{\link{Prior_reduced}} \link{Prior_reduced}.
#' @param ntrees The number of trees used to build the RF classifier.
RF_build_abcrf<- function(ReducedPrior,FullPrior,ntrees){
  Models <- as.factor(FullPrior[,'Model'])
  Trainingdata <- data.frame(Models, ReducedPrior)
  RF <- abcrf::abcrf(Models~., data = Trainingdata, ntree=ntrees, paral = TRUE)
  return(RF)
}

#' Predict the model for the observed data
#' @export
#' @importFrom stats predict
#' @param Observed_Reduced The observed data as prepared using the function \code{\link{prepobserved}} \link{prepobserved}.
#' @param ReducedPrior This should be the prior with invariant columns removed, as created by the function \link{Prior_reduced}.
#' @param FullPrior This should be the full prior as generated by the function \code{\link{makeprior}} \link{makeprior}.
#' @param ntrees The number of trees to use in the RF classifier.
#' @param RF The RF classifier built using the function \code{\link{RF_build_abcrf}} \link{RF_build_abcrf}.
RF_predict_abcrf <- function(RF, Observed_Reduced, ReducedPrior, FullPrior, ntrees){
  Models <- as.factor(FullPrior[,'Model'])
  Trainingdata <- data.frame(Models, ReducedPrior)
  Prediction <- predict(object=RF, obs=Observed_Reduced, training = Trainingdata, paral = TRUE, paral.predict = TRUE, ntree = ntrees)
  #Prediction <- predict(object = myRF, obs = Observed_Reduced,training = Trainingdata,paral = TRUE, paral.predict = TRUE, ntree = ntrees)
  return(Prediction)
}


